apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: it-diagnostics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:10.1.2
        ports:
          - containerPort: 3000
        volumeMounts:
          # Dashboard JSON ConfigMap
          - name: grafana-dashboard
            mountPath: /var/lib/grafana/dashboards

          # Dashboard provider ConfigMap
          - name: grafana-dashboard-provider
            mountPath: /etc/grafana/provisioning/dashboards

          # Datasources ConfigMap
          - name: grafana-datasources
            mountPath: /etc/grafana/provisioning/datasources

      volumes:
        - name: grafana-dashboard-configmap
          configMap:
            name: grafana-dashboard-configmap

        - name: grafana-dashboard-provider
          configMap:
            name: grafana-dashboard-provider

        - name: grafana-datasources
          configMap:
            name: grafana-datasources

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: it-diagnostics
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
      name: http

